const path = {
  PUBLIC: "tonghop",
  HOME: "",
  LOGIN: "",
  DANHMUC: "DanhMuc",
  DANHMUC_NH: "DanhMuc_NhomHang",
  DANHMUC_HH: "DanhMuc_HangHoa",
  DANHMUC_NDT: "DanhMuc_NhomDoiTuong",
  DANHMUC_DT: "DanhMuc_DoiTuong",
  DANHMUC_HMT: "DanhMuc_HangMucThu",
  DANHMUC_HMC: "DanhMuc_HangMucChi",
  TRUYVAN_CNDV: "TruyVan_CongNoDauVao",
  TRUYVAN_CNDR: "TruyVan_CongNoDauRa",
  TRUYVAN_DSHH: "TruyVan_DoanhSoBanHangHH",
  TRUYVAN_DSKH: "TruyVan_DoanhSoBanHangKH",
  TRUYVAN_CDNXT_TK: "TruyVan_CanDoiNXT_TheoKho",
  THIETLAP_NGDT: "ThietLap_NhomGiaDoiTuong",
  THIETLAP_GIALE: "ThietLap_GiaLe",
  THIETLAP_GIASI: "ThietLap_GiaSi",
  DULIEU_PMH: "DuLieu_PMH",
  DULIEU_NDC: "DuLieu_NDC",
  DULIEU_XDC: "DuLieu_XDC",
  DULIEU_PBH: "DuLieu_PBS",
  DULIEU_PTT: "DuLieu_PTT",
  DULIEU_PCT: "DuLieu_PCT",
};
export default path;
